server:
  port: 8002

spring:
  application:
    name: payment

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.siwen.entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
     prefer-ip-address: true
     instance-id: payment8002
